server:
  port: 8085
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    #    platform: postgres
    #    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/codream
    username: codream_worker
    password: p@@sZxcv5bn
#    cassandra:
#      port: 9042
#      contact-points: localhost
#      keyspace-name: codreaming_keyspace
#      schema-action: create_if_not_exists

