server:
  port: 8085
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    #    platform: postgres
    #    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/codream
    username: codream_worker
    password: p@@sZxcv5bn
#    cassandra:
#      port: 9042
#      contact-points: localhost
#      keyspace-name: codreaming_keyspace
#      schema-action: create_if_not_exists

security:
  oauth2:
    client:
      clientId: 686666634207-qc5ndod6ps99svo52pl8p7p11oqlp5cr.apps.googleusercontent.com
      clientSecret: yGTt3Xu4DXwfejelFM2KyZW9
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth?hd=xyz.com
      redirectUri: http://localhost:8080
      clientAuthenticationScheme: form
        #        tokenName: oauth_token
      #        authenticationScheme: query
      scope:
        - email
        - profile
      resource:
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
        preferTokenInfo: true
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me